### ISSUE TITLE
How do I use this TOC generator on my Jekyll site

### ISSUE THREAD

**Issue by fusion809** [gajus/contents#16]
Is it possible to use this TOC generator on my [Jekyll-powered GitHub Pages website](https://fusion809.github.io)?

I've managed to use other people's TOC generator jQuery scripts to do this, by simply adding the script to my [js folder](https://github.com/fusion809/fusion809.github.io/blob/master/js) and including it in my [_layouts/default.html](https://github.com/fusion809/fusion809.github.io/blob/master/_layouts/default.html) file using `<script src="/js/toc.js" type="text/javascript"></script>` tags.

Is something like this possible with your TOC generator?

**Comment by gajus** [comment]
Sure. You just need to download the browser build (https://github.com/gajus/contents/tree/master/dist/browser). After that have a look at the [quick start](https://github.com/gajus/contents#quick-start) docs and the [working examples](https://github.com/gajus/contents#examples).

**Comment by fusion809** [comment]
OK, well I downloaded the browser build `contents.js` script to `/js`, added the quick start JavaScript at the end of `/js/contents.js` and included `<script src="/js/contents.js" type="text/javascript"></script>` in my default.html file but this gave the error: `Uncaught ReferenceError: require is not defined`. Guessing that means that the require function is not defined in my `/js/jquery.js` script. Would a good solution to this problem be to run `npm install contents` in my Jekyll site root directory, add two lines to default.html, namely:

```html
<script src="/node_modules/jquery/dist/jquery.js"></script>
<script src="/node_modules/contents/dist/browser/contents.js"></script>
```

I'm guessing this would solve the problem based on the contents of https://github.com/gajus/contents/blob/master/examples/jquery/index.html

**Comment by gajus** [comment]
```
Uncaught ReferenceError: require is not defined
```

There is not one reference of `require` in https://raw.githubusercontent.com/gajus/contents/master/dist/browser/contents.js. Therefore, the error is very likely coming from another script.
