### ISSUE TITLE
[eslint]  new-cap violation

### ISSUE THREAD

**Issue by brcolow** [gajus/contents#18]
Hi,

I am currently using contents in an environment with pretty strict eslint settings:

```json
{
  "extends": ["airbnb-base"],
  "env": {
    "browser": true,
    "jquery": true
  },
  "rules": {
    "comma-dangle": ["error", "never"],
    "indent": ["error", 4, {"SwitchCase": 1}],
    "linebreak-style": "off",
    "max-len": ["error", 120],
    "no-underscore-dangle": ["error", { "allowAfterThis": true}]
  }
}
```

I import contents at the top of my module like so:

```javascript
import Contents from 'contents';
```
and then use it like so:

```javascript
 const contents = Contents({ *stuff* });
```

When running eslint on my project, I obtain the following rule violation:

> A function with a name starting with an uppercase letter should only be used as a constructor (new-cap)

Trying to use:

```javascript
import * as contents from 'contents';
```

also does not suppress the violation because you still need to then reference the capitalized `Contents` 

Would it be possible for you to either rename it to `contents` (a very breaking change) or somehow expose two instances, one `contents` and the other already existing `Contents`.

Thanks very much.

**Comment by gajus** [comment]
When you are using syntax `import foo from 'bar'`, you choose the name of the import, i.e. `foo` can be anything. Therefore, the following are equivalent:

```js
import Contents from 'contents';
import contents from 'contents';
```

**Comment by brcolow** [comment]
Oh jeez. Clearly I am new to Ecmascript 6 and javascript in general! Thanks for the prompt response.
