### ISSUE TITLE
Does contents require headers to be siblings of children for the generation of TOC?

### ISSUE THREAD

**Issue by BoPeng** [gajus/contents#29]
We are trying to generate TOCs for a bunch of Jupyter notebooks. We tried to use jquery.tocify.js but it has one major limitations for this kind of documents. That is to say, [it requires headers to be siblings or children of each other](https://github.com/gfranko/jquery.tocify.js/issues/36), which does not work for our documents because all headers are in their cells and the layout looks something like:

```
cell -> h2
cell -> h3
cell -> h3
cell -> h2
```
jquery.tocify.js would produce a TOC with only `h2` because `h3`s are not children of `h2`. Will contents be able to handle this case?

**Comment by gajus** [comment]
TIAS
